version: 2
jobs:
   compile_test: 
     docker: 
       - image: "debian:stretch"
     steps:
       - run:
           name: Installing SUDO
           command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
       - run:
           name: Installing SSH
           command: 'apt-get update && apt-get install -y ssh'
       - run:
           name: Installing GIT
           command: 'apt-get update && apt-get install -y git'
       - run:
           name: Installing GCC
           command: 'apt-get update && apt-get install -y gcc g++'
       - run:
           name: Install CMAKE
           command: 'apt-get update && sudo apt-get install -y cmake'
       - checkout 
       - run: mkdir build 
       - run: ls -a
       - run: cd build && cmake ..

workflows:
   version: 2
   all:
     jobs:
       - compile_test
