version: 2
jobs:
    build: 
     docker: 
       - image: "debian:stretch"
     steps:
       - run:
           name: Installing SUDO
           command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
       - run:
           name: Installing SSH
           command: 'apt-get update && apt-get install -y ssh'
       - run:
           name: Installing GIT
           command: 'apt-get update && apt-get install -y git'
       - run:
           name: Installing GCC
           command: 'apt-get update && apt-get install -y gcc g++'
       - run:
           name: Install CMAKE
           command: 'apt-get update && sudo apt-get install -y cmake'
       - run:
           name: Install pkg-config
           command: 'apt-get update && sudo apt-get install -y pkg-config'
       - run:
           name: Install GLIB
           command: 'apt-get update && sudo apt-get install -y libgtk2.0-dev'
       - run:
           name: Install ncurses
           command: 'apt-get update && sudo apt-get install -y libncurses5-dev libncursesw5-dev'
       - checkout 
    cmake: 
     docker: 
       - image: "debian:stretch"
     steps:
       - run: mkdir build 
       - run: cd build && cmake ..
    cmake_test:
     docker: 
       - image: "debian:stretch"
     steps:
       - run: make 
       - run: cd build && cmake .. -DBuildTests=ON
    execute_test:
     docker: 
       - image: "debian:stretch"
     steps:
       - run: make check_main
       - run: ./build/tests/check_main

workflows:
   version: 2
   all:
     jobs:
       - build
       - cmake:
           requires:
             build
       - cmake_test:
           requires:
             build
       - execute_test:
           requires:
             build
             cmake_test
       
