version: 2
jobs:
    cmake: 
     docker: 
       - image: ubuntu-1604:201903-01
     steps:
       - run:
           name: update
           command: 'apt-get update'
       - run:
           name: Installing SSH
           command: 'apt-get install -y ssh'
       - run:
           name: Installing GIT
           command: 'apt-get install -y git'
       - run:
           name: Installing GCC
           command: 'apt-get install -y gcc'
       - run:
           name: Install CMAKE
           command: 'apt-get install -y cmake'
       - run:
           name: Install pkg-config
           command: 'apt-get install -y pkg-config'
       - run:
           name: Install GLIB
           command: 'apt-get install -y libgtk2.0-dev'
       - run:
           name: Install ncurses
           command: 'apt-get install -y libncurses5-dev libncursesw5-dev'
       - checkout 
       - run: mkdir build 
       - run: cd build && cmake ..
    cmake_test:
     docker: 
       - image: ubuntu-1604:201903-01
     steps:
       - run:
           name: update
           command: 'apt-get update'
       - run:
           name: Installing SSH
           command: 'apt-get install -y ssh'
       - run:
           name: Installing GIT
           command: 'apt-get install -y git'
       - run:
           name: Installing GCC
           command: 'apt-get install -y gcc'
       - run:
           name: Install CMAKE
           command: 'apt-get install -y cmake'
       - run:
           name: Install pkg-config
           command: 'apt-get install -y pkg-config'
       - run:
           name: Install GLIB
           command: 'apt-get install -y libgtk2.0-dev'
       - run:
           name: Install ncurses
           command: 'apt-get install -y libncurses5-dev libncursesw5-dev'
       - run:
           name: Install check
           command: 'apt-get install -y check'
       - checkout 
       - run: mkdir build 
       - run: cd build && cmake .. -DBuildTests=ON
       - persist_to_workspace:
            root: .
            paths:
                - build
    execute_test:
     docker: 
       - image: ubuntu-1604:201903-01
     steps:
       - attach_workspace:
            at: build
       - run:
           name: update
           command: 'apt-get update'
       - run:
           name: Installing SSH
           command: 'apt-get install -y ssh'
       - run:
           name: Installing GIT
           command: 'apt-get install -y git'
       - run:
           name: Installing GCC
           command: 'apt-get install -y gcc'
       - run:
           name: Install CMAKE
           command: 'apt-get install -y cmake'
       - run:
           name: Install pkg-config
           command: 'apt-get install -y pkg-config'
       - run:
           name: Install GLIB
           command: 'apt-get install -y libgtk2.0-dev'
       - run:
           name: Install ncurses
           command: 'apt-get install -y libncurses5-dev libncursesw5-dev'
       - run:
           name: Install check
           command: 'apt-get install -y check'
       - checkout 
       - run: cd build && make check_main
       - run: ./build/tests/check_main

workflows:
   version: 2
   all:
     jobs:
       - cmake
       - cmake_test
       - execute_test:
           requires:
             - cmake_test
       
