version: 2
jobs:
   compile_test: 
     docker: 
       - image: circleci/ruby:2.4.1 
     steps:
       - checkout 
       - run: mkdir build 
       - run: cd build
       - run: cmake ..

workflows:
   version: 2
   all:
     jobs:
       - compile_test
