# Use the official image as a parent image.
FROM "debian:stretch"

# Run the command inside your image filesystem.
RUN apt-get update

RUN apt-get install -y ssh && apt-get install -y git && apt-get install -y gcc && apt-get install -y cmake && apt-get install -y pkg-config && apt-get install -y libgtk2.0-dev && apt-get install -y libncurses5-dev libncursesw5-dev
